### ISSUE TITLE
Highlight the requirements 

### ISSUE THREAD

**Issue by tireddy2** [SpencerDawkins/net-collab-rqmts#8]
It will be helpful to highlight the requirements associated with each use case, for instance, see https://datatracker.ietf.org/doc/rfc7478/

**Comment by sridharangirish91** [comment]
In use cases, will it make sense to follow the below format to make it clear?

Use case:
Problem: 
Solution How signaling helps/solves:

**Comment by tireddy2** [comment]
> In use cases, will it make sense to follow the below format to make it clear?
> 
> Use case: Problem: Solution How signaling helps/solves:

Use cases and requirements format should suffice, see RFC7478.

**Comment by sridharangirish91** [comment]
I took a shot at coming up with requirements for Media traffic type (Interactive and Streaming) to state the intent, requirement and the use case to focus on the need more than the way to solve it. Kind of kept the language generic without specifying whether it is a client to network or server to network so that this is applicable in P2P cases too. Please share your comments on the format. I put together the content from both signaling and hdr-wireless doc. Once we get the format fixed, I can expand it to other sections as well.

[RequirementsFormat.md](https://github.com/SpencerDawkins/net-collab-rqmts/files/15349795/RequirementsFormat.md)
